#ifndef MAIN_H
#define MAIN_H

#include <iostream>
#include <vector>
#include <cmath>
#include <random>
#include <sstream>
#include <fstream>
#include <string>
#include <iomanip>
#include <cstring>
#include <functional>
#include <cstdint>
#include <cassert>
#include <tuple>
#include <algorithm>
#include <numeric>
#include <thread>
#include <mutex>

/**
 * AISignal struct represents a trading signal generated by the AI
 * Contains timepoint, action type (BUY/SELL), predicted price, and signal strength
 */
struct AISignal {
    int timeIdx;
    enum Action { BUY, SELL } type;
    double predictedPrice;
    double magnitude; // How strong the signal is
};

/**
 * Generate a random V4 UUID string
 * Returns a string representing a UUID v4 with 2^122 possible values
 * @return UUID string in format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 */
std::string generateUuidV4();

/**
 * Constants for the simulation
 */
const int POINTS_PER_DAY = 510; // 510 minutes in a trading day (8:00 to 16:30)
const double DEFAULT_S0 = 500.0;      // Default initial stock price
const int DEFAULT_DIFFICULTY = 2;     // Default AI difficulty level (1-4)
const double DEFAULT_MU = 0.05;       // Default drift parameter
const double DEFAULT_SIGMA = 0.4;     // Default volatility parameter
const double DEFAULT_SENTIMENT = 0.0; // Default market sentiment

#endif // MAIN_H
